# Site settings
title: saminiir's blog
email: saminiir@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Yet Another Hacker Blog (YAHB).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: saminiir
github_username:  saminiir

# Build settings
markdown: kramdown

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about.html
